/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FindMeMainPanel.java
 *
 * Created on Mar 9, 2011, 3:54:19 PM
 */

package org.ezuce.panels;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JLayeredPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.swingx.JXLabel;
import org.jdesktop.swingx.JXPanel;
import org.jdesktop.swingx.JXSearchField;
import org.jdesktop.swingx.JXSearchField.LayoutStyle;
import org.jdesktop.swingx.prompt.BuddySupport.Position;


/**
 *
 * @author Razvan
 */
public class FindMeMainPanel extends javax.swing.JPanel {

    /** Creates new form FindMeMainPanel */
    public FindMeMainPanel() {
        initComponents();
        customize();
    }

    /**
     * Performs customization of the components inside the panel.
     */
    protected void customize()
    {
        final Icon lensIcon=Images.searchFieldLensIcon;
        List<Component> buddies=jXSearchField.getBuddies(Position.LEFT);
        for (Component c:buddies)
           {
               if (c instanceof JButton)
               {
                   final JButton btn=(JButton)c;
                   btn.setIcon(lensIcon);
               }
           }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLayeredPaneTop = new JLayeredPane();
        jButtonSubmit = new JButton();
        jXSearchField = new JXSearchField();
        jXLabelSearchFieldBg = new JXLabel();
        jXLabelTopBackground = new JXLabel();
        jXPanelContents = new JXPanel();

        setBorder(BorderFactory.createLineBorder(new Color(177, 177, 177)));

        jLayeredPaneTop.setMaximumSize(new Dimension(350, 37));
        jLayeredPaneTop.setMinimumSize(new Dimension(350, 37));
        jLayeredPaneTop.setName("jLayeredPaneTop"); // NOI18N

        ResourceMap resourceMap = Application.getInstance().getContext().getResourceMap(FindMeMainPanel.class);
        jButtonSubmit.setIcon(resourceMap.getIcon("jButtonSubmit.icon")); // NOI18N
        jButtonSubmit.setBorder(null);
        jButtonSubmit.setBorderPainted(false);
        jButtonSubmit.setContentAreaFilled(false);
        jButtonSubmit.setDoubleBuffered(true);
        jButtonSubmit.setFocusPainted(false);
        jButtonSubmit.setHideActionText(true);
        jButtonSubmit.setName("jButtonSubmit"); // NOI18N
        jButtonSubmit.setRolloverIcon(resourceMap.getIcon("jButtonSubmit.rolloverIcon")); // NOI18N
        jButtonSubmit.setBounds(270, 6, 80, -1);
        jLayeredPaneTop.add(jButtonSubmit, JLayeredPane.DEFAULT_LAYER);

        jXSearchField.setLayoutStyle(LayoutStyle.MAC);
        jXSearchField.setPrompt("Find contact");
        jXSearchField.setPromptFontStyle(Font.PLAIN);
        jXSearchField.setUseNativeSearchFieldIfPossible(false);
        jXSearchField.setDoubleBuffered(true);
        jXSearchField.setFont(new Font("Arial", 0, 12));
        jXSearchField.setName("jXSearchField"); // NOI18N
        jXSearchField.setOpaque(false);
        jXSearchField.setBounds(10, 10, 250, 20);
        jLayeredPaneTop.add(jXSearchField, JLayeredPane.DEFAULT_LAYER);
        jXSearchField.setBorder(null);

        jXLabelSearchFieldBg.setIcon(resourceMap.getIcon("jXLabelSearchFieldBg.icon")); // NOI18N
        jXLabelSearchFieldBg.setDoubleBuffered(true);
        jXLabelSearchFieldBg.setIconTextGap(0);
        jXLabelSearchFieldBg.setInheritsPopupMenu(false);
        jXLabelSearchFieldBg.setName("jXLabelSearchFieldBg"); // NOI18N
        jXLabelSearchFieldBg.setBounds(2, 0, 270, 40);
        jLayeredPaneTop.add(jXLabelSearchFieldBg, JLayeredPane.DEFAULT_LAYER);

        jXLabelTopBackground.setIcon(resourceMap.getIcon("jXLabelTopBackground.icon")); // NOI18N
        jXLabelTopBackground.setName("jXLabelTopBackground"); // NOI18N
        jXLabelTopBackground.setBounds(0, 0, 350, 37);
        jLayeredPaneTop.add(jXLabelTopBackground, JLayeredPane.DEFAULT_LAYER);

        jXPanelContents.setName("jXPanelContents"); // NOI18N

        GroupLayout jXPanelContentsLayout = new GroupLayout(jXPanelContents);
        jXPanelContents.setLayout(jXPanelContentsLayout);
        jXPanelContentsLayout.setHorizontalGroup(
            jXPanelContentsLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jXPanelContentsLayout.setVerticalGroup(
            jXPanelContentsLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jLayeredPaneTop, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE)
            .addComponent(jXPanelContents, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPaneTop, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jXPanelContents, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents

    public JButton getSubmitButton()
    {
        return this.jButtonSubmit;
    }

    public JXSearchField getSearchField()
    {
        return this.jXSearchField;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonSubmit;
    private JLayeredPane jLayeredPaneTop;
    private JXLabel jXLabelSearchFieldBg;
    private JXLabel jXLabelTopBackground;
    private JXPanel jXPanelContents;
    private JXSearchField jXSearchField;
    // End of variables declaration//GEN-END:variables

}
