package org.ezuce.media.ui;

import java.awt.event.FocusEvent;
import javax.swing.ImageIcon;
import org.ezuce.common.resource.EzucePresenceUtils;
import org.ezuce.common.resource.Utils;
import org.ezuce.common.ui.wrappers.ContactItemWrapper;
import org.ezuce.common.ui.wrappers.interfaces.ContactListEntry;
import org.ezuce.common.ui.wrappers.interfaces.UserMiniPanelCommonInterface;
import org.jivesoftware.smackx.packet.VCard;
import org.jivesoftware.spark.SparkManager;

import static org.apache.commons.lang3.StringUtils.isEmpty;
import static org.apache.commons.lang3.StringUtils.EMPTY;

/**
 *
 * @author Razvan
 */
public class AudioCallAvatarPanel extends javax.swing.JPanel 
                                  implements UserMiniPanelCommonInterface{

    private ContactListEntry contact;
    
    /**
     * Creates new form AudioCallAvatarPanel
     */
    public AudioCallAvatarPanel() {
        initComponents();
    }
    
    public AudioCallAvatarPanel(ContactListEntry cle)
    {
        this.contact = cle;
        initComponents();
        customizeForContact();
    }
    
    public final void customizeForContact() {
        if (contact!=null) {
        	updateVCardData();
            if (contact.getPresence()==null) {
                //setUserStatusIcon(Images.userStatusOffline);
                setUserStatus(EzucePresenceUtils.getUpdatedUserStatus(null));
            }
            else {
                //updateStatus(contact.getPresence());
            }
        }
    }
    
    private void updateVCardData() {
        setUserDisplayName(isEmpty(contact.getUserDisplayName()) ? contact.getNumber() : contact.getUserDisplayName());
        setDescription(isEmpty(contact.getDescription()) ? EMPTY : contact.getDescription());
        setUserStatus(isEmpty(contact.getStatus()) ? EMPTY : contact.getStatus());
        final ImageIcon avatar= contact.getUserAvatar();
        if (avatar!=null) {                 
           setUserPicture(avatar);
        } 
    }

    public void setUserPicture(ImageIcon im)
    {
        if (im!=null){            
            this.audioCallMugshotPanel.setMugshot(im);
        }
        else {
            this.remove(this.audioCallMugshotPanel);
            this.audioCallMugshotPanel=null;    
            this.repaint();
        }
    }
    
    
    public void setContact(ContactListEntry cle)
    {
        this.contact=cle;
    }
    
    @Override
    public ContactListEntry getContact() {
        return this.contact;
    }

    @Override
    public String getJID() {        
        return (contact instanceof ContactItemWrapper) ? ((ContactItemWrapper)contact).getContactItem().getJID() : null;
    }

    @Override
    public String getExtension() {
        if (contact instanceof ContactItemWrapper) {
        	String jid = ((ContactItemWrapper)contact).getContactItem().getJID();
        	return Utils.getExtension(jid);
        }
        else {
            return contact.getNumber();
        }
    }

    public void setUserDisplayName(String displayName)
    {
        this.jLabelDisplayName.setText(displayName);
    }        
    
    @Override
    public String getUserDisplayName() {
        return this.jLabelDisplayName.getText();
    }
    
    public void setDescription(String details)
    {
        this.jLabelUserDetails.setText(details);
    }
    
    public String getDescription()
    {
        return this.jLabelUserDetails.getText();
    }
    
    public void setUserStatus(String status)
    {
        this.jLabelUserStatus.setText(status);
    }
    
    public String getUserStatus()
    {
        return this.jLabelUserStatus.getText();
    }

    @Override
    public void focusGained(FocusEvent e) {
        
    }

    @Override
    public void focusLost(FocusEvent e) {
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        audioCallMugshotPanel = new org.ezuce.media.ui.AudioCallMugshotPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        jPanelDetails = new javax.swing.JPanel();
        jLabelDisplayName = new javax.swing.JLabel();
        jLabelUserDetails = new javax.swing.JLabel();
        jLabelUserStatus = new javax.swing.JLabel();

        setAlignmentY(0.5F);
        setMaximumSize(new java.awt.Dimension(32823, 53));
        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        audioCallMugshotPanel.setMaximumSize(new java.awt.Dimension(48, 53));
        audioCallMugshotPanel.setMinimumSize(new java.awt.Dimension(48, 53));
        audioCallMugshotPanel.setName("audioCallMugshotPanel"); // NOI18N
        audioCallMugshotPanel.setPreferredSize(new java.awt.Dimension(48, 53));

        javax.swing.GroupLayout audioCallMugshotPanelLayout = new javax.swing.GroupLayout(audioCallMugshotPanel);
        audioCallMugshotPanel.setLayout(audioCallMugshotPanelLayout);
        audioCallMugshotPanelLayout.setHorizontalGroup(
            audioCallMugshotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        audioCallMugshotPanelLayout.setVerticalGroup(
            audioCallMugshotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        add(audioCallMugshotPanel);

        filler1.setName("filler1"); // NOI18N
        add(filler1);

        jPanelDetails.setMaximumSize(new java.awt.Dimension(500, 53));
        jPanelDetails.setMinimumSize(new java.awt.Dimension(52, 53));
        jPanelDetails.setName("jPanelDetails"); // NOI18N
        jPanelDetails.setOpaque(false);
        jPanelDetails.setLayout(new javax.swing.BoxLayout(jPanelDetails, javax.swing.BoxLayout.PAGE_AXIS));

        jLabelDisplayName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDisplayName.setForeground(new java.awt.Color(46, 85, 102));
        jLabelDisplayName.setText("User Name");
        jLabelDisplayName.setDoubleBuffered(true);
        jLabelDisplayName.setName("jLabelDisplayName"); // NOI18N
        jPanelDetails.add(jLabelDisplayName);

        jLabelUserDetails.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelUserDetails.setForeground(new java.awt.Color(116, 116, 116));
        jLabelUserDetails.setText("Details");
        jLabelUserDetails.setDoubleBuffered(true);
        jLabelUserDetails.setName("jLabelUserDetails"); // NOI18N
        jPanelDetails.add(jLabelUserDetails);

        jLabelUserStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelUserStatus.setForeground(new java.awt.Color(116, 116, 116));
        jLabelUserStatus.setText("Status");
        jLabelUserStatus.setDoubleBuffered(true);
        jLabelUserStatus.setName("jLabelUserStatus"); // NOI18N
        jPanelDetails.add(jLabelUserStatus);

        add(jPanelDetails);
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    private org.ezuce.media.ui.AudioCallMugshotPanel audioCallMugshotPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabelDisplayName;
    private javax.swing.JLabel jLabelUserDetails;
    private javax.swing.JLabel jLabelUserStatus;
    private javax.swing.JPanel jPanelDetails;
    // End of variables declaration                   
}
