/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EzuceSubjectPanel.java
 *
 * Created on Nov 22, 2011, 10:52:45 PM
 */
package org.ezuce.im.ui;

/**
 *
 * @author Razvan
 */
public class EzuceSubjectPanel extends javax.swing.JPanel {	
    private javax.swing.JLabel jLabelRoomName;    	   
    
    public EzuceSubjectPanel(String roomType, String roomName){
        initComponents();
        
        this.jLabelRoomName.setText("<html><font size=4><b>"+roomName +"</b></font> <font size=3>" + roomType+"</font></html>");
    }
    
    public EzuceSubjectPanel(String roomType, String roomName, String subject){
        initComponents();
        this.jLabelRoomName.setText("<html><font size=4><b>"+roomName +
                "</b></font> <font size=3>" + roomType+" </font>"
                + "<font size=3><b>&nbsp;&nbsp;&nbsp; Subject:</b></font> <font size=3>"+(subject==null?"none":subject)+"</font></html>");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabelRoomName = new javax.swing.JLabel();

        setFocusable(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabelRoomName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRoomName.setForeground(new java.awt.Color(46, 85, 102));
        jLabelRoomName.setText("Room Name");
        jLabelRoomName.setDoubleBuffered(true);
        jLabelRoomName.setFocusable(false);
        jLabelRoomName.setName("jLabelRoomName"); // NOI18N
        add(jLabelRoomName);
    }
}
