/*
 * EzuceChatHeaderContainer.java
 *
 * Created on Nov 30, 2011, 12:26:22 AM
 */
package org.ezuce.im.ui;

/**
 *
 * @author Razvan
 */
public class EzuceChatHeaderContainer extends javax.swing.JPanel {

    /** Creates new form EzuceChatHeaderContainer */
    public EzuceChatHeaderContainer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(32767, 196));
        setMinimumSize(new java.awt.Dimension(22, 22));
        setOpaque(false);        
        setLayout(new org.jdesktop.swingx.VerticalLayout());
    }
}
