package sources;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

public class ScreenSharingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScreenSharingJPanel
     */
    public ScreenSharingJPanel() {
        initComponents();
    }

    public JButton getBtnStopScreenSharing() {
        return btnStopScreenSharing;
    }

    public JToggleButton getBtnTglMouse() {
        return btnTglMouse;
    }

    public JToggleButton getBtnTglPauseVideo() {
        return btnTglPauseVideo;
    }

    public JLabel getLblStatus() {
        return lblStatus;
    }

    public JLabel getLblStatusIcon() {
        return lblStatusIcon;
    }

    public JTextField getTxtDuration() {
        return txtDuration;
    }
    
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }
    
    

    public boolean isStatus() {
        return stare;
    }
    public void setStare(boolean stare) {
        this.stare = stare;
    }
    

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(stare){
        ImageIcon ii = resourceMap.getImageIcon("Background");
        if (ii != null) {
            Image i = ii.getImage();
            if (i != null) {
                g.drawImage(i, 0, 0, getWidth(), getHeight(),
                        0, 0, ii.getIconWidth(), ii.getIconHeight(), null);
            }
        }
        }
        else
        {
            this.setBackground(resourceMap.getColor("BackgroudAccept"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatusIcon = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnTglMouse = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        txtDuration = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnStopScreenSharing = new javax.swing.JButton();
        btnTglPauseVideo = new javax.swing.JToggleButton();

        setName("Form"); // NOI18N

        lblStatusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/connecting.png"))); // NOI18N
        lblStatusIcon.setName("lblStatusIcon"); // NOI18N

        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(102, 102, 102));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sources/resources/ScreenSharingJPanel"); // NOI18N
        lblStatus.setText(bundle.getString("ScreenSharingJPanel.lblStatus.text")); // NOI18N
        lblStatus.setMaximumSize(new java.awt.Dimension(133, 25));
        lblStatus.setMinimumSize(new java.awt.Dimension(133, 25));
        lblStatus.setName("lblStatus"); // NOI18N
        lblStatus.setPreferredSize(new java.awt.Dimension(133, 25));

        btnTglMouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/mouse-control_off.png"))); // NOI18N
        btnTglMouse.setBorder(null);
        btnTglMouse.setBorderPainted(false);
        btnTglMouse.setContentAreaFilled(false);
        btnTglMouse.setDoubleBuffered(true);
        btnTglMouse.setFocusPainted(false);
        btnTglMouse.setName("btnTglMouse"); // NOI18N
        btnTglMouse.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/mouse-control_on.png"))); // NOI18N
        btnTglMouse.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/mouse-control_off_indication.png"))); // NOI18N
        btnTglMouse.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/mouse-control_on_indication.png"))); // NOI18N
        btnTglMouse.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/mouse-control_on.png"))); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);

        txtDuration.setEditable(false);
        txtDuration.setBackground(new java.awt.Color(255, 255, 255));
        txtDuration.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDuration.setForeground(new java.awt.Color(0, 51, 51));
        txtDuration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDuration.setText(bundle.getString("ScreenSharingJPanel.txtDuration.text")); // NOI18N
        txtDuration.setMaximumSize(new java.awt.Dimension(47, 25));
        txtDuration.setMinimumSize(new java.awt.Dimension(47, 25));
        txtDuration.setName("txtDuration"); // NOI18N
        txtDuration.setPreferredSize(new java.awt.Dimension(47, 25));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(txtDuration, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(txtDuration, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);

        btnStopScreenSharing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/close_off.png"))); // NOI18N
        btnStopScreenSharing.setBorder(null);
        btnStopScreenSharing.setBorderPainted(false);
        btnStopScreenSharing.setContentAreaFilled(false);
        btnStopScreenSharing.setDoubleBuffered(true);
        btnStopScreenSharing.setFocusPainted(false);
        btnStopScreenSharing.setHideActionText(true);
        btnStopScreenSharing.setName("btnStopScreenSharing"); // NOI18N
        btnStopScreenSharing.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/close_on.png"))); // NOI18N
        btnStopScreenSharing.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/close_on.png"))); // NOI18N

        btnTglPauseVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/hold_off.png"))); // NOI18N
        btnTglPauseVideo.setBorder(null);
        btnTglPauseVideo.setBorderPainted(false);
        btnTglPauseVideo.setContentAreaFilled(false);
        btnTglPauseVideo.setDoubleBuffered(true);
        btnTglPauseVideo.setFocusPainted(false);
        btnTglPauseVideo.setName("btnTglPauseVideo"); // NOI18N
        btnTglPauseVideo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/hold_off.png"))); // NOI18N
        btnTglPauseVideo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/hold_on2.png"))); // NOI18N
        btnTglPauseVideo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/hold_on2.png"))); // NOI18N
        btnTglPauseVideo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/resources/hold_on1.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(btnTglPauseVideo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnStopScreenSharing)
                .add(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnStopScreenSharing)
                    .add(btnTglPauseVideo))
                .add(0, 0, 0))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(lblStatusIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(btnTglMouse)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(lblStatus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lblStatusIcon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnTglMouse)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(3, 3, 3))
        );

        lblStatusIcon.getAccessibleContext().setAccessibleDescription(bundle.getString("ScreenSharingJPanel.lblStatusIcon.AccessibleContext.accessibleDescription")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStopScreenSharing;
    private javax.swing.JToggleButton btnTglMouse;
    private javax.swing.JToggleButton btnTglPauseVideo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusIcon;
    private javax.swing.JTextField txtDuration;
    // End of variables declaration//GEN-END:variables
    final ResourceMap resourceMap = Application.getInstance().getContext().getResourceMap(ScreenSharingJPanel.class);

    private boolean stare = true;
    
    
}
