/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CounterJPanel.java
 *
 * Created on Apr 26, 2011, 11:52:15 PM
 */

package org.ezuce.panels;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentListener;

import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 *
 * @author Razvan
 */
public class CounterJPanel extends javax.swing.JPanel {

    /** Creates new form CounterJPanel */
    public CounterJPanel() {
        initComponents();
        jButtonIncrease.setActionCommand(INCREASE_ACTION_COMMAND);
        jButtonDecrease.setActionCommand(DECREASE_ACTION_COMMAND);
        activate(Boolean.TRUE);
    }
    
    public void addDocumentListener(DocumentListener listener) {
    	jTextFieldMins.getDocument().addDocumentListener(listener);
    	jTextFieldSecs.getDocument().addDocumentListener(listener);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLayeredPane = new JLayeredPane();
        jPanelInactive = new JPanel();
        jLabel = new JLabel();
        jPanelActive = new JPanel();
        jButtonIncrease = new JButton();
        jTextFieldMins = new JTextField();
        jLabelSeparator = new JLabel();
        jTextFieldSecs = new JTextField();
        jButtonDecrease = new JButton();

        jLayeredPane.setName("jLayeredPane"); // NOI18N

        jPanelInactive.setFocusable(false);
        jPanelInactive.setMaximumSize(new Dimension(66, 20));
        jPanelInactive.setMinimumSize(new Dimension(66, 20));
        jPanelInactive.setName("jPanelInactive"); // NOI18N
        jPanelInactive.setOpaque(false);
        jPanelInactive.setPreferredSize(new Dimension(66, 20));

        jLabel.setHorizontalAlignment(SwingConstants.CENTER);
        ResourceMap resourceMap = Application.getInstance().getContext().getResourceMap(CounterJPanel.class);
        jLabel.setIcon(resourceMap.getIcon("jLabel.icon")); // NOI18N
        jLabel.setVerticalAlignment(SwingConstants.TOP);
        jLabel.setDoubleBuffered(true);
        jLabel.setFocusable(false);
        jLabel.setMaximumSize(new Dimension(66, 20));
        jLabel.setMinimumSize(new Dimension(66, 20));
        jLabel.setName("jLabel"); // NOI18N
        jLabel.setPreferredSize(new Dimension(66, 20));

        GroupLayout jPanelInactiveLayout = new GroupLayout(jPanelInactive);
        jPanelInactive.setLayout(jPanelInactiveLayout);
        jPanelInactiveLayout.setHorizontalGroup(
            jPanelInactiveLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(jLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelInactiveLayout.setVerticalGroup(
            jPanelInactiveLayout.createParallelGroup(Alignment.LEADING)
            .addComponent(jLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelInactive.setBounds(0, 0, -1, -1);
        jLayeredPane.add(jPanelInactive, JLayeredPane.DEFAULT_LAYER);

        jPanelActive.setMaximumSize(new Dimension(67, 20));
        jPanelActive.setMinimumSize(new Dimension(67, 20));
        jPanelActive.setName("jPanelActive"); // NOI18N
        jPanelActive.setPreferredSize(new Dimension(67, 20));
        jPanelActive.setLayout(new BoxLayout(jPanelActive, BoxLayout.LINE_AXIS));

        jButtonIncrease.setIcon(resourceMap.getIcon("jButtonIncrease.icon")); // NOI18N
        jButtonIncrease.setBorder(null);
        jButtonIncrease.setBorderPainted(false);
        jButtonIncrease.setContentAreaFilled(false);
        jButtonIncrease.setDoubleBuffered(true);
        jButtonIncrease.setFocusPainted(false);
        jButtonIncrease.setHideActionText(true);
        jButtonIncrease.setName("jButtonIncrease"); // NOI18N
        jButtonIncrease.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonIncreaseActionPerformed(evt);
            }
        });
        jPanelActive.add(jButtonIncrease);

        jTextFieldMins.setColumns(2);
        jTextFieldMins.setEditable(false);
        jTextFieldMins.setFont(new Font("Arial", 0, 12));
        jTextFieldMins.setForeground(new Color(116, 116, 116));
        jTextFieldMins.setHorizontalAlignment(JTextField.CENTER);
        jTextFieldMins.setText("00");
        jTextFieldMins.setBorder(null);
        jTextFieldMins.setDoubleBuffered(true);
        jTextFieldMins.setFocusable(false);
        jTextFieldMins.setName("jTextFieldMins"); // NOI18N
        jTextFieldMins.setOpaque(false);
        jPanelActive.add(jTextFieldMins);

        jLabelSeparator.setForeground(new Color(116, 116, 116));
        jLabelSeparator.setText(":");
        jLabelSeparator.setName("jLabelSeparator"); // NOI18N
        jPanelActive.add(jLabelSeparator);

        jTextFieldSecs.setColumns(2);
        jTextFieldSecs.setEditable(false);
        jTextFieldSecs.setFont(new Font("Arial", 0, 12));
        jTextFieldSecs.setForeground(new Color(116, 116, 116));
        jTextFieldSecs.setHorizontalAlignment(JTextField.CENTER);
        jTextFieldSecs.setText("15");
        jTextFieldSecs.setBorder(null);
        jTextFieldSecs.setDoubleBuffered(true);
        jTextFieldSecs.setFocusable(false);
        jTextFieldSecs.setName("jTextFieldSecs"); // NOI18N
        jTextFieldSecs.setOpaque(false);
        jPanelActive.add(jTextFieldSecs);

        jButtonDecrease.setIcon(resourceMap.getIcon("jButtonDecrease.icon")); // NOI18N
        jButtonDecrease.setBorder(null);
        jButtonDecrease.setBorderPainted(false);
        jButtonDecrease.setContentAreaFilled(false);
        jButtonDecrease.setDoubleBuffered(true);
        jButtonDecrease.setFocusPainted(false);
        jButtonDecrease.setHideActionText(true);
        jButtonDecrease.setName("jButtonDecrease"); // NOI18N
        jButtonDecrease.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonDecreaseActionPerformed(evt);
            }
        });
        jPanelActive.add(jButtonDecrease);

        jPanelActive.setBounds(0, 0, 67, 20);
        jLayeredPane.add(jPanelActive, JLayeredPane.DEFAULT_LAYER);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jLayeredPane, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jLayeredPane, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );
    }//GEN-END:initComponents

    private void jButtonIncreaseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonIncreaseActionPerformed
        this.increaseValue();
    }//GEN-LAST:event_jButtonIncreaseActionPerformed

    private void jButtonDecreaseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonDecreaseActionPerformed
        this.decreaseValue();
    }//GEN-LAST:event_jButtonDecreaseActionPerformed

    public int getMinutes()
    {
        return Integer.parseInt(this.jTextFieldMins.getText());
    }

    public int getSeconds()
    {
        return Integer.parseInt(this.jTextFieldSecs.getText());
    }

    public String getValue()
    {
        return this.jTextFieldMins.getText()+
                this.jLabelSeparator.getText()+
                this.jTextFieldSecs.getText();
    }

    public void setMinutes(int mins)
    {
        this.jTextFieldMins.setText(String.format("%02d", mins));
    }

    public void setSeconds(int secs)
    {
        this.jTextFieldSecs.setText(String.format("%02d", secs));
    }

    public JButton getIncreaseButton()
    {
        return this.jButtonIncrease;
    }

    public JButton getDecreaseButton()
    {
        return this.jButtonDecrease;
    }

    public Boolean isActive()
    {
        return this.active;
    }

    public void setActive(Boolean activeStatus)
    {
        this.active=activeStatus;
        this.activate(activeStatus);
    }

    /**
     * Enables the component in order for the user to be able to modify the values
     * using the up/down buttons.
     * @param flag
     */
    protected void activate(Boolean flag)
    {
        if (flag==null) flag=Boolean.FALSE;

        this.jPanelInactive.setVisible(!flag);
        this.jButtonIncrease.setVisible(flag);
        this.jButtonDecrease.setVisible(flag);
    }

    private void increaseValue()
    {
        this.setSeconds(this.getSeconds()+1);
        if (this.getSeconds()==60)
        {
            this.setSeconds(0);
            this.setMinutes(this.getMinutes()+1);
        }
    }

    private void decreaseValue()
    {
        this.setSeconds(this.getSeconds()-1);
        if (this.getSeconds()==-1)
        {
            this.setSeconds(59);
            this.setMinutes(this.getMinutes()-1);
            if (this.getMinutes()==-1) this.setMinutes(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonDecrease;
    private JButton jButtonIncrease;
    private JLabel jLabel;
    private JLabel jLabelSeparator;
    private JLayeredPane jLayeredPane;
    private JPanel jPanelActive;
    private JPanel jPanelInactive;
    private JTextField jTextFieldMins;
    private JTextField jTextFieldSecs;
    // End of variables declaration//GEN-END:variables
    private Boolean active;
    public static final String INCREASE_ACTION_COMMAND="increase command";
    public static final String DECREASE_ACTION_COMMAND="decrease command";

}
